# CertificateSigningRequest — client cert for CN=ht (kube-apiserver-client signer)
#
# Cluster-scoped — NO metadata.namespace (ignored if set).
# spec.request = base64(ht.csr) — regenerate after new openssl CSR:
#   cat ht.csr | base64 | tr -d '\n'
#
# Workflow:
#   kc apply -f csr.yaml
#   kc get csr ht
#   kc certificate approve ht
#   kc get csr ht -o jsonpath='{.status.certificate}' | base64 -d > ht.crt
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ht
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1VqQ0NBVG9DQVFBd0RURUxNQWtHQTFVRUF3d0NhSFF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUUNXUjVIRzkwT0s1Qkhzc1ZVQS9hTEt6UkZ0RjVxM3lOMU16a1FDRmN3TWVBQk1oNjJ3ClpLVmFsSGNhcW84QnVWOHNmNURjRGFPUXJ0MXVUbWpCQm1RSkwxMnRZWEduUllDK0tHYkZLRU52ZzdXVXJFZzEKa0pSQVhkeXBkb2plMUNxNlJkbVYrUWU1SmxSTHhtVVY5akY1NXl6bTd4MzYreC9CcTlLYmJWRmJTSE8zRWdMVwpBL25FeFhoTjhtWlFlTkZ1NlJTSVJpSTd4Y2JRYWVjNXdnQjJtS0xtbHdNYmwremVKOFNLTGJBbEF2cGFPNmkzCnI5OGlBdHRMZnZZa2NFUDRsREZLVHQwN291RXRtT0kzNTB5M0prLzVTTGZkeEFFWWdHRzQvSm5vK1dXMGh1OFcKMDZneVJzYXFPL3V4bGF1d0N5d1lrWGFibWpFYzFVa2lnTnRGQWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQWdHbzkzVGlZSXluclYvVlJETmppSVpOOFp5cXV2cmsvcmhUWTdSU1dJckl0R1Npa0JZdFlVWHhzCmFxL0MrcHhEWnNWVk1jQmNSYk1oQVliazROZUl2YktwZ2VEZ3Jld1YrYUU2dDRiTDRydzNMUlNPR2pqdTEyaksKenhoaFduNjZJME1BamxXejY4ckV1SSsxVHdHaDE0MUoxVjVMc3dMSE1BQWhYaTBBVm9MaGxvRlJaZnRVZGhZcAoxaEVRM3BBQ0JiZXdzMWxTTWUrVTA5eC9ZNW5oWGlicmExUjNDeERpUmFjOUVYYWp4a2gxS25qSnNEZXlicUZWCjZzcDRlTjZsWUllbXBFTkNvaWtPOHE3WkROWmdjbnY3bzAwUWVZWGE2UE1NeUxmU0YxbDdldGtJK2c2N1VXZnYKaFVuQmJOWkJyS0o5WmR4QUZlL1I0OUM5M3hHalZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
  - client auth
