#!/usr/bin/env bash
# Enable multi-cluster Grafana dashboards (15757/15760) on obs Prometheus.
# Run on obs master after install-dev-metrics.sh on dev:
#   DEV_TARGET=10.110.100.184:30301 bash configure-obs-multicluster.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEV_TARGET="${DEV_TARGET:-}"
DEV_KUBECONFIG="${DEV_KUBECONFIG:-${HOME}/.kube/dev-config}"

if [[ -z "${KUBECONFIG:-}" ]]; then
  if [[ -f "${HOME}/.kube/config" ]]; then
    export KUBECONFIG="${HOME}/.kube/config"
  else
    export KUBECONFIG="/etc/kubernetes/admin.conf"
  fi
fi

if [[ -z "${DEV_TARGET}" ]]; then
  echo "ERROR: set DEV_TARGET to dev KSM NodePort, e.g. 10.110.100.184:30301" >&2
  exit 1
fi

if ! kubectl get nodes >/dev/null 2>&1; then
  echo "ERROR: kubectl cannot reach obs cluster." >&2
  exit 1
fi

if ! command -v helm >/dev/null 2>&1; then
  echo "ERROR: helm not found on obs master." >&2
  exit 1
fi

if [[ ! -f "${DEV_KUBECONFIG}" ]]; then
  echo "ERROR: ${DEV_KUBECONFIG} missing — copy dev kubeconfig to obs-master" >&2
  exit 1
fi

DEV_MASTER_IP="${DEV_TARGET%%:*}"
KSM_NODEPORT="${DEV_TARGET##*:}"
mapfile -t DEV_NODE_IPS < <(kubectl --kubeconfig "${DEV_KUBECONFIG}" get nodes -o jsonpath='{range .items[*]}{.status.addresses[?(@.type=="InternalIP")].address}{"\n"}{end}')

echo "==> Connectivity obs → dev"
for ip in "${DEV_NODE_IPS[@]}"; do
  nc -vz -w 3 "${ip}" 9100 </dev/null 2>&1 | tail -1 || echo "WARN: ${ip}:9100 blocked"
done
nc -vz -w 3 "${DEV_MASTER_IP}" "${KSM_NODEPORT}" </dev/null 2>&1 | tail -1 || echo "WARN: ${DEV_TARGET} blocked"

BASE_VALUES="${SCRIPT_DIR}/../manifests/obs/prometheus-values.yaml"
if [[ ! -f "${BASE_VALUES}" ]]; then
  echo "ERROR: ${BASE_VALUES} not found — git pull on obs-master" >&2
  exit 1
fi

# Pass dev node IPs to Python (one per line)
DEV_IPS_FILE="/tmp/dev-node-ips.txt"
printf '%s\n' "${DEV_NODE_IPS[@]}" > "${DEV_IPS_FILE}"

python3 <<PY
from pathlib import Path
dev_ips = Path("${DEV_IPS_FILE}").read_text().splitlines()
dev_targets_yaml = "\n".join(f'          - "{ip}:9100"' for ip in dev_ips if ip.strip())
footer = Path("${BASE_VALUES}").read_text().split("alertmanager:", 1)[1]

extra = f'''extraScrapeConfigs: |
  - job_name: obs-kube-state-metrics
    static_configs:
      - targets: ["prometheus-kube-state-metrics.observability.svc.cluster.local:8080"]
    metric_relabel_configs:
      - target_label: cluster
        replacement: obs
  - job_name: obs-node-exporter
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '\${{1}}:9100'
        target_label: __address__
      - target_label: cluster
        replacement: obs
      - target_label: job
        replacement: obs-node-exporter
    metric_relabel_configs:
      - target_label: cluster
        replacement: obs
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector.observability.svc.cluster.local:8889"]
    metric_relabel_configs:
      - target_label: cluster
        replacement: obs
  - job_name: dev-node-exporter
    static_configs:
      - targets:
{dev_targets_yaml}
    relabel_configs:
      - target_label: cluster
        replacement: dev
      - target_label: job
        replacement: dev-node-exporter
    metric_relabel_configs:
      - target_label: cluster
        replacement: dev
  - job_name: dev-kube-state-metrics
    static_configs:
      - targets: ["${DEV_MASTER_IP}:${KSM_NODEPORT}"]
    relabel_configs:
      - target_label: cluster
        replacement: dev
      - target_label: job
        replacement: kube-state-metrics
    metric_relabel_configs:
      - target_label: cluster
        replacement: dev
'''

header = '''# generated by configure-obs-multicluster.sh
server:
  global:
    scrape_interval: 15s
  persistentVolume:
    enabled: false

'''
Path("/tmp/prometheus-obs-values.yaml").write_text(header + extra + "alertmanager:" + footer)
print("Wrote /tmp/prometheus-obs-values.yaml")
PY

echo "==> Validating YAML"
if python3 -c "import yaml" 2>/dev/null; then
  python3 -c "import yaml; from pathlib import Path; yaml.safe_load(Path('/tmp/prometheus-obs-values.yaml').read_text()); print('YAML OK')"
else
  echo "SKIP: python3-yaml not installed — helm will validate"
fi

echo "==> Upgrading obs Prometheus"
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts >/dev/null 2>&1 || true
helm repo update
helm upgrade --install prometheus prometheus-community/prometheus \
  -n observability \
  --set kube-state-metrics.prometheus.monitor.enabled=false \
  --set prometheus-node-exporter.prometheus.monitor.enabled=false \
  --set prometheus-node-exporter.prometheus.podMonitor.enabled=false \
  -f /tmp/prometheus-obs-values.yaml

kubectl rollout status -n observability deployment/prometheus-server --timeout=300s || true
sleep 20

echo ""
echo "==> Verify dev targets"
curl -sf http://127.0.0.1:9090/api/v1/targets 2>/dev/null | python3 -c "
import json,sys
try:
    d=json.load(sys.stdin)
except Exception:
    print('Run: kubectl port-forward -n observability svc/prometheus-server 9090:80')
    sys.exit(0)
for t in d['data']['activeTargets']:
    if 'dev' in t['labels'].get('job',''):
        print(t['health'], t['scrapeUrl'])
" || echo "(port-forward 9090 if empty)"
