{
 "title": "SLI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "burn rated",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_server_requests_seconds_count{\n    namespace=\"retail-store\",\n    app_kubernetes_io_instance=\"retail-store-ui\",\n    status=~\"5..\",\n    uri!~\"/actuator.*\"\n  }[5m]))\n  /\n  sum(rate(http_server_requests_seconds_count{\n    namespace=\"retail-store\",\n    app_kubernetes_io_instance=\"retail-store-ui\",\n    uri!~\"/actuator.*\"\n  }[5m]))\n)\n/ 0.001\nor on() vector(0)"
    }
   ]
  },
  {
   "title": "error budget consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(http_server_requests_seconds_count{\n    namespace=\"retail-store\",\n    app_kubernetes_io_instance=\"retail-store-ui\",\n    status=~\"5..\",\n    uri!~\"/actuator.*\"\n  }[6h]))\n  /\n  (\n    sum(increase(http_server_requests_seconds_count{\n      namespace=\"retail-store\",\n      app_kubernetes_io_instance=\"retail-store-ui\",\n      uri!~\"/actuator.*\"\n    }[6h]))\n    * 0.001\n  )\n)\n* 100\nor on() vector(0)"
    }
   ]
  },
  {
   "title": "Store UI | 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app_kubernetes_io_instance=\"retail-store-ui\",status=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Store UI | 2xx & 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app_kubernetes_io_instance=\"retail-store-ui\",status!=\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "cart SLI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orders 2xx and 4xx",
     "type": "timeseries",
     "description": "Query A : Calculates the per-second average rate of increase of the time series in the range vector.\n\nQuery B: Calculates the increase in the time series in the range vector",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-cart\",status!=\"5..\"}[5m]))"
      }
     ]
    },
    {
     "title": "Orders 5xx",
     "type": "timeseries",
     "description": "Query A : Calculates the per-second average rate of increase of the time series in the range vector.\n\nQuery B: Calculates the increase in the time series in the range vector\n\nor on() vector(0) -> will be 0 if no 5xx",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-cart\",status=~\"5..\"}[5m])) or on() vector(0)"
      }
     ]
    },
    { "title": "burn rate", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 } },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "description": "Query A : Calculates the per-second average rate of increase of the time series in the range vector.\n\nQuery B: Calculates the increase in the time series in the range vector",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "((sum(rate(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-cart\",status=~\"5..\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-cart\"}[5m]))) * 100) or on() vector(0)"
      }
     ]
    },
    {
     "title": "error budget consumption",
     "type": "gauge",
     "description": "(5xx/total)/0.001 as SLO is 99.99% while performing math in formula decimal values are used.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(rate(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-cart\",status=~\"5..\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-cart\"}[5m]))/0.001)) * 100 or on() vector(0)"
      }
     ]
    }
   ]
  },
  { "title": "order SLI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Orders 2xx and 4xx", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 } },
  { "title": "Orders 5xx", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 } },
  { "title": "Error Rate", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 } },
  {
   "title": "burn rate",
   "type": "timeseries",
   "description": "(5xx/total)/0.001 as SLO is 99.99%",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "((sum(rate(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-order\",status=~\"5..\"}[5m]))/sum(rate(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-order\"}[5m]))/0.001)) or on() vector(0)"
    }
   ]
  },
  { "title": "error budget consumption", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 } },
  {
   "title": "Total Successfull Requests | 2xx & 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"retail-store\",app_kubernetes_io_instance=\"retail-store-orders\",status!=\"5..\"}[5m]))"
    }
   ]
  }
 ]
}