apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: order-api
  labels:
    app.kubernetes.io/name: order-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: order-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
