apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-new
spec:
  containers:
  - image: nginx
    name: nginx-new
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
