apiVersion: v1
kind: Service
metadata:
  labels:
    env: demo
  name: nodeport-svc
spec:
  ports:
  - name: nodeport-svc-port
    nodePort: 31593
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      env: demo 
  type: NodePort
