apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-container
        image: hthaware2508/ingress-demo-app:v1
        ports:
        - containerPort: 8080