# kubeadm EC2 cluster — uses NodePort values (no AWS LB)
# Prerequisite: Argo CD installed on cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/htpractice/ht-study.git
    targetRevision: cka-2026-study
    path: Kubernetes/CICD-Day/helm/order-api
    helm:
      valueFiles:
        - values-kubeadm.yaml
  destination:
    name: dev
    namespace: order-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
